import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <script async="async" data-cfasync="false" src="//pl17130843.safestgatetocontent.com/ecbc16c92962b0bc17ffc7af7c07f444/invoke.js"></script>
        {/* eslint-disable-next-line @next/next/no-sync-scripts */}
        <script type='text/javascript' src='//pl17131205.safestgatetocontent.com/01/69/83/016983db6bfdb0d7d46208b99df74829.js'></script>
      </Head>
        <div id="container-ecbc16c92962b0bc17ffc7af7c07f444"></div>
        <div className="flex flex-col">
          <div className="bg-gray-100 rounded rounded-xl z-40 flex flex-col w-1/2 self-center p-4">
          <p className="text-2xl text-center">Join this Telegram link for getting direct product links</p>
          <a className="text-center bg-blue-500 w-40 self-center mt-7 text-white rounded rounded-xl animate-bounce p-3" href="https://www.safestgatetocontent.com/s08bvqxwnf?key=50cac4fa7a28aac4a90fabbbad8c4246">
            Join Telegram
          </a>
          <p className="text-sm mt-4 text-center">**Sorry for bad design, Our team is working to make it a full e-commerce site</p>
          </div>
        </div>
        <div id="container-ecbc16c92962b0bc17ffc7af7c07f444"></div>
    </div>
  )
}
